### ISSUE TITLE
Strange behavior on changing screen size

### ISSUE THREAD

**Issue by gtkovas** [adazzle/react-data-grid#100]
When placing a ReactDataGrid element into a div, resizing the screen area (by minimizing then maximizing, or for instance by popping up developers tools and resizing that) the rendered area of the ReactDataGrid will constantly grow horizontally, each time the rendering window size changes.

I have reproduced this behavior using the code from the "Basic Example" provided on the RDG examples page. The behavior presents on both Chrome and Firefox.

Attached is an html file (saved as .txt so I could upload it) called "sizing_test" containing the webpage I used to reproduce the bug. I'm still thinking of a way to create a failing test for this kind of thing, but decided to create the issue with the info I have.

[sizing_test.txt](https://github.com/adazzle/react-data-grid/files/33103/sizing_test.txt)

**Comment by madprog** [comment]
For those interested, I could hack-fix this by setting a `max-width: 100vw;` CSS property on a parent element.
The problem is that `ReactDataGrid` is looking at the viewport width, which was larger than the window because of the grid itself, so it was never decreasing the width of the grid.
However, I'm afraid that this will only work properly if your grid is taking the whole width of your window. You may need to write a `calc(100vw - xxx)` if you have other elements.
