### ISSUE TITLE
Set (Header) Row Height in other units

### ISSUE THREAD

**Issue by amber-workxpress** [adazzle/react-data-grid#1032]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

---

### Issue Details

Current behavior: It seems like `rowHeight` and `headerRowHeight` only accept number values corresponding to px, which makes it difficult to scale on the basis of browser font size, etc.

Desired behavior: Can we have the ability to pass in, for example, `"2em"` or `"2rem"` instead of only inputting numbers?

Motivation/use case: Our application is meant to allow for a variety of custom user styling, which may include different font sizes, etc. Being able to always set the row height to, say, twice the font height using em would be useful.

**Comment by jpdriver** [comment]
hey @amber-workxpress -- good idea! since we're using `PropTypes`, we currently have simple validation checking that the type passed in is numeric.

In order to support strings with `px|em|rem` we'd need to write a custom validator function that would split the string up and then validate the unit and numeric value separately.

we'd probably then have the allowed PropType be either `Number` or `String` (assuming Number and `px` by default) and use the custom validator for `String` values.

should be possible!

**Comment by malonecj** [comment]
Closing this for now, as there are no plans to work on it. We are adding a roadmap to the project shortly, and the feature requests that are deemed most useful will be added to it
