### ISSUE TITLE
cell range selection copy & paste 

### ISSUE THREAD

**Issue by kamaldlk** [adazzle/react-data-grid#1037]
@amanmahajan7  cell range any possible please give me suggestion. im so long waiting.   please help me im using in production most needed function :(

**Comment by ZackKnopp** [comment]
Okay, here it is, cell range copy-paste functionality built on top of react-data-grid.

You can copy from external sources and paste into the grid as well. Anything outside of the current grid is truncated, because my use-case needs this.

https://gist.github.com/ZackKnopp/40fc0691feb03f0fba3e25e7353b73ae
