### ISSUE TITLE
cell range selection copy, paste and delete like google sheet possible

### ISSUE THREAD

**Issue by kamaldlk** [adazzle/react-data-grid#1043]
Guys  any can implement this option within 2days i'll give u min 200$ max 300$ because to urgent for me. 
@jpdriver  im trying to complete this task.
 
feel free please connect with me 
skype : kamaldlk
email: kamalcdsk@gmail.com

**Comment by jpdriver** [comment]
@kamaldlk I understand you need this feature but please stop bugging us. I'd like to see it in a future release of React Data Grid too, but right now it isn't available and it isn't being actively worked on. If you need it immediately I would suggest using an alternative like AG grid. Thanks and good luck.

**Comment by kamaldlk** [comment]
Sorry @jpdriver thanks

**Comment by ZackKnopp** [comment]
Okay, here it is, cell range copy-paste functionality built on top of react-data-grid.

You can copy from external sources and paste into the grid as well. Anything outside of the current grid is truncated, because my use-case needs this.

https://gist.github.com/ZackKnopp/40fc0691feb03f0fba3e25e7353b73ae
