### ISSUE TITLE
Preserve Table Expanded State

### ISSUE THREAD

**Issue by venkateshreddy** [adazzle/react-data-grid#1058]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes.
- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [x] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details

```
Please include:
- What the current behavior is
Table is not preserving the state if the rows are rerendered.
- What the desired behvaior is
If the table is expanded and rerendered with new data or new props. The preserved expanded state should remain the table as it was.
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature
If preserving the expanded state feature is available. we can control the expanded state of the table.
This will be more powerfull. 

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

**Comment by diogofcunha** [comment]
Hi @venkateshreddy, although internally when a row is expanded some local state is set to make sure it expands straight away it isn't the grid's responsibility to keep that state when new props are injected, the grid shouldn't be opinionated about either the rows should keep expansion or not, that's up to the user and it can have different variations depending on the use case.

Keeping the selection is possible from day 1, because when a cell is expanded [onCellExpand is invoked](https://github.com/adazzle/react-data-grid/blob/e7b5fbfa30bc097d6ed4993e348b50430ffb6178/packages/react-data-grid/src/CellExpand.js#L26) and that means that you can save the expansion value against the row.

**Comment by venkateshreddy** [comment]
Thanks Diogo.
Will try it.
