### ISSUE TITLE
Problem with Rendering 

### ISSUE THREAD

**Issue by Thorbenandresen** [adazzle/react-data-grid#130]
Hi,

I am just getting started with this module, but I cant get it to render:

![screen shot 2015-12-04 at 8 11 37 pm](https://cloud.githubusercontent.com/assets/8238976/11605031/7092c344-9ac3-11e5-8065-bad32d242e1c.jpg)
What am I missing? 

I am using this boilerplate: https://github.com/gaearon/react-hot-boilerplate

and here is my module:

```
var React = require('react');
var ReactDataGrid = require('../node_modules/react-data-grid/dist/react-data-grid.js');

var _rows = [];
for (var i = 1; i < 1000; i++) {
  _rows.push({
    id: i,
    title: 'Title ' + i,
    count: i * 1000
  });
}

//A rowGetter function is required by the grid to retrieve a row for a given index
var rowGetter = function(i){
  return _rows[i];
};


var columns = [
{
  key: 'id',
  name: 'ID'
},
{
  key: 'title',
  name: 'Title'
},
{
  key: 'count',
  name: 'Count'
}
]

export default class Example extends React.Component {
  render() {
    return (
      <ReactDataGrid
    columns={columns}
    rowGetter={rowGetter}
    rowsCount={_rows.length}
    minHeight={500} />

    );
  }
}

module.exports = Example


```

**Comment by jpdriver** [comment]
hey @Thorbenandresen -- i've just had a look into this and it's because `react-hot-boilerplate` uses React 14 :disappointed:

we're working on supporting that here https://github.com/adazzle/react-data-grid/pull/63 but it's not *quite* ready for primetime just yet..

you could try checking out the `cm-react-14-upgrade` and using `npm link` to develop against that locally, but i haven't tested that branch so i can't guarantee it will work.

unfortunately the only other option is to find an alternative for react-hot-boilerplate. sorry!

**Comment by jpdriver** [comment]
hey @Thorbenandresen -- our latest release uses React 14 so you can re-try this now. please let us know how you get on. cheers!

**Comment by Thorbenandresen** [comment]
@jpdriver thanks a lot! I'll give it go
