### ISSUE TITLE
Don't freeze checkbox / selection column

### ISSUE THREAD

**Issue by sontek** [adazzle/react-data-grid#1386]
- Have you already searched for similar issues? Please help us out and double-check first!
Yes, I've also looked at the code.

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [X] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [X] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [X] 🐛 Bug Report
- [X] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
I'm trying to use the `rowSelection` property to add a checkbox column onto my table.  But it is setting `frozen: true` which is unexpected behavior.   I don't want, need, or like the frozen behavior.  It means when my table is on mobile the space is used up by the checkbox so they view less data.  The setting seems to be here:

https://github.com/adazzle/react-data-grid/blob/faa881114626d14d3fbb6e34b80cd1c08095cd31/packages/react-data-grid/src/ReactDataGrid.js#L632

Can you at least offer an option like `rowSelection { freeze: false }`?

**Comment by sontek** [comment]
This is actually a problem on more than mobile even though that was my original concern.    The frozen columns is really delayed and so the user experience isn't great for what we are trying to provide our users.    So I think just a setting to say "don't freeze checkbox columns" would be enough for us.

![nov-19-2018 12-33-33](https://user-images.githubusercontent.com/151924/48721055-7b20d980-ebf7-11e8-93d7-1b77cc868633.gif)

**Comment by shreyamdg** [comment]
Are you sure? It works great for me!

![ezgif-1-7e46dd60dd87](https://user-images.githubusercontent.com/26554257/49449605-e09cca80-f7a0-11e8-982c-12704173e76c.gif)

**Comment by sontek** [comment]
Are you using an old version?  I have no idea how you got it to not freeze that column since you can see in the code I pointed to that its definitely freezing them.

It also appears in the demo:
http://adazzle.github.io/react-data-grid/docs/examples/row-selection

If you shrink the screen enough to get the columns that way.

**Comment by sontek** [comment]
This is only stale because I haven't received a response yet.  This issue still exists.

**Comment by sontek** [comment]
This still hasn't been addressed

**Comment by zekehernandez** [comment]
I am having the same issue with frozen columns in general. In Chrome, the issue only happens when I use my MacBook trackpad and not from moving the scrollbar (it also happens no matter what in Firefox, but that's not a supported browser). Simply making the columns not frozen would not be a solution for my use case, however.

Here is an example of me using the codesandbox demo for frozen columns in Chrome:
![react-data-grid](https://user-images.githubusercontent.com/1766586/53201086-bb259d00-35e8-11e9-85d4-600a9241ef6b.gif)

**Comment by sontek** [comment]
I don't think this is stale.  We haven't heard from the maintainers on it but its definitely still a problem that is causing me and my customers pain =)

**Comment by sontek** [comment]
I wish the stale bot would stop closing good tickets

**Comment by Brentox** [comment]
Issue still exists. Keep open

**Comment by eduardosmatheus** [comment]
Shouldn't it be buggy because of the ReactJS version in use? I'm having the same issue and my project is using v16.8.6.

I'm looking for a solution as well, and maybe there's not enough support in current releases with 16.x ReactJS features (?).

**Comment by liamzhang40** [comment]
The same concern here on mobile. A way to adjust to checkbox column width will also be helpful. Besides, the delayed rendering is really not the most appealing

**Comment by liamzhang40** [comment]
After investigating the stuttering behavior of frozen columns, I found out that it has something to do with trackpads' inertial scrolling which is the decelerating part of page scrolling after you lift fingers off the trackpad. And scroll/mousewheel events still fire during it. Therefore in Viewport.tsx, https://github.com/adazzle/react-data-grid/blob/4e9efe98907c0bed0da07ecfdd5ef7f579601db5/packages/react-data-grid/src/Viewport.tsx#L42
``isScrolling`` is updated with a delay with some debouncing on top of it.

Such pattern appears to also cause table headers' horizontal moves more slowly compared to that of table body. 
Two obstacles I had attempting to work around this. One is to disable inertial scrolling. The other one is to hijack Canvas.tsx handleScroll because I will need access to scroll events if I want to disable inertial scrolling. 
https://github.com/adazzle/react-data-grid/blob/4e9efe98907c0bed0da07ecfdd5ef7f579601db5/packages/react-data-grid/src/Canvas.tsx#L334 

I have been stuck on this and any help will be appreciated.

**Comment by tareqaal** [comment]
I solved it using CSS. I targeted the following cells to stop the transform property which make this user delay experiance:

`.react-grid-Row .react-grid-Cell--frozen {
    transform: translate3d(0px, 0px, 0px) !important!
}
.react-grid-HeaderRow .react-grid-HeaderCell--frozen {
            transform: translate3d(0px, 0px, 0px) !important;
        }`

**Comment by liamzhang40** [comment]
> I solved it using CSS. I targeted the following cells to stop the transform property which make this user delay experiance:
> 
> `.react-grid-Row .react-grid-Cell--frozen { transform: translate3d(0px, 0px, 0px) !important! }`
> ` .react-grid-HeaderRow .react-grid-HeaderCell--frozen { transform: translate3d(0px, 0px, 0px) !important; }`
> 
> PS: the header check box cells is separate than the row body.

You just made the frozen columns always stay at the left of the viewport but they need to move as users scroll so it appears to be frozen. Do you mind showing a demo if it is actually working for you?

**Comment by beygorghor** [comment]
Hi, i have the same issue, any update ?

**Comment by jsalinas11** [comment]
Same issue here. Would like a response.

**Comment by amanmahajan7** [comment]
This can be achieved in v7 canary

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/CommonFeatures.tsx#L45

you should be able to do 

```
const columns: readonly Column<Row, SummaryRow>[] = [
  { SelectColumn, frozer: false },
  ...
```
