### ISSUE TITLE
Is there a way to reject a cell selection after a click?

### ISSUE THREAD

**Issue by mashaod** [adazzle/react-data-grid#1516]
I want to reject a cell selection by right mouse bottom while cellRangeSelection area is existing. It will help to create a context menu for cellRangeSelection area.

**Comment by colindjk** [comment]
Not a fix exactly, but instead of using ContextMenu to work with cellSelectionRange, why not add toolbar buttons / components that are only visible / enabled when cellRangeSelection exists for an area > 1x1. 

That way you can interact with the toolbar while you've selected a range and work with the range however you want. 

Otherwise, unfortunately for now, right clicking while having a `cellSelectionRange` will deselect the given range.
