### ISSUE TITLE
Cell editor flows around if data-grid is placed inside scrollable component

### ISSUE THREAD

**Issue by szogun1987** [adazzle/react-data-grid#1548]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

### Issue Details
When:
editable data-grid is placed inside scrollable container 
and user starts editing cell
and scroll using mouse wheel or touchpad guests
Then
Editor goes out cell

Issue is reproducible in [here](https://codesandbox.io/s/qx9y6y1qz4)

**Comment by szogun1987** [comment]
It seem's that it is fixable by passing editorPortal property, please document it better.

**Comment by SteveDowsett** [comment]
> It seem's that it is fixable by passing editorPortal property, please document it better.

Im having this issue also, could someone explain how to solve this as its a blocker for us.

**Comment by amanmahajan7** [comment]
Closing this issue as it fixed by `editorPortalTarget` prop. We also recommend upgrading to canary as it does not have a lot of the old issues 
https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
