### ISSUE TITLE
Use keyboard enter to trigger row selection while selected cell is on the checkbox

### ISSUE THREAD

**Issue by johnstsai** [adazzle/react-data-grid#1604]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [ ] 🐛 Bug Report
- [x] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

Hi I am wondering if we can trigger onRowSelected select row by press enter while the cell select is on the checkbox? Current behavior is not able to select row by press enter but need mouse click.
Thanks!

**Comment by amanmahajan7** [comment]
This is fixed in v7 canary. Now checkbox can be selected with spacebar (default checkbox behavior). You can customize it so the checkbox is toggled on enter

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos
