### ISSUE TITLE
Selected cell outline is visible by default and cannot be changed

### ISSUE THREAD

**Issue by ekros** [adazzle/react-data-grid#1655]
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [x] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [x] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

---

### Issue Details
After updating the library from v2 to v5 I see that selected cells have a blue outline, even if cell selection is disabled, which does not make sense to me. Is this a wanted behavior or a bug? Is there any workaround? Thanks.
```

**Comment by nwhitmont** [comment]
I just ran into this same issue after upgrading from `4.0.7` to `5.0.4`.

Blue outline is highly undesirable.  

It shows up on the first upper left cell on page load when nothing has been selected by the user.
<img width="301" alt="Screen Shot 2020-03-18 at 7 49 06 PM" src="https://user-images.githubusercontent.com/3075047/77026713-96b60480-6951-11ea-8e2b-f8360aac72f3.png">

How to disable it?

**Comment by ekros** [comment]
I updated recently from v4 to v6 and I am getting the top-left cell outlined without interacting with the grid. @nwhitmont have you found a way to disabled it or a workaround?

**Comment by amber-cd** [comment]
Seeing this issue as well... specifically, I'm noticing that if I select a cell and then click away from it, the blue outline persists. Looks like this is the behavior as seen in the demos. Is there a workaround or other way around this? We're updating from v4 to v6 in order to resolve an autofocus issue, but we don't want fields to appear that they have focus when they no longer do.

**Comment by amber-cd** [comment]
Some additional findings: as near as I can tell, it seems like the actual selected style isn't being applied to the individual cell, but rather there's a separate div at the top of the list with the `rdg-selected` class. That div then uses a transform so that it appears over the top of whichever cell is selected. The div doesn't appear until you first click on one of the cells (or at least doesn't in my use case, but might explain the issue where the top-left cell appears to have been selected when the List loads for others), and then never disappears when you click out of the List entirely, hence the problem.

I was able to work around this for now by adding this to my styles:

```
.rdg-selected {
	border: 0px !important
}
```

But I don't really think that's a long-term solution, as it's not super friendly for sighted keyboard users, who can still navigate using the keyboard but who don't have a good way to tell which cell is selected.

**Comment by ekros** [comment]
@amber-cd thanks! It did the trick.

I don't worry about keyboard navigation because I'm not using cell selection. You could add a keyboard listener to re-enable the blue box when arrows are pressed (just another quick fix, not a solution).

**Comment by nstepien** [comment]
Closing this as we do not support previous versions of `react-data-grid` anymore.
Please try the latest version, currently `7.0.0-beta.2`.
If you still run into issues with the latest version, please open a _new_ issue.
