### ISSUE TITLE
rowHeight to accept auto

### ISSUE THREAD

**Issue by txm** [adazzle/react-data-grid#190]
currently you can fix the height of a row with

rowHeight={60}

It would be better if it could accept auto

rowHeight={auto}

**Comment by jpdriver** [comment]
hey @txm -- `rowHeight` does need to be a number, so our PropTypes are blocking that by design.

If you adjust the element style using Dev Tools on the examples, you'll see that with `height:auto;` the row disappears because it renders as 0 by 0 px.

![image](https://cloud.githubusercontent.com/assets/2393035/12675695/0849573e-c684-11e5-9534-f3f24bfe5adf.png)

if your content won't fit in the standard height (35px) you'll need to override it by passing in a new number. sorry!

**Comment by bakesteve** [comment]
Yes – internally we have to know the rowHeight to calculate the canvas height, and which rows are in view.
The grid does not have access to all your data (which makes it fast) so cant know how big the content will actually be for row 100-120 while rendering only rows 1-25.
That’s assuming you are wanting auto rowHeight so that different rows are different heights? Rather than so that the grid can figure the height needed based off the 1st row?
If it’s the later, that would still be tricky (we use rowHeight way before we have rendered any rows) but I’d guess not impossible (would need some form of render that produce the row, worked out its height, in the initialisation of the grid. But would definitely be a bit complex, and probably best done outside of the grid itself by leveraging rowRenderer

**Comment by fierascu** [comment]
For me, a fix was setting rowHeight={60} and also had to fix children in css:
```
.rdg-child-cell .react-grid-Cell__value {
  line-height: 60px !important
}
```
