### ISSUE TITLE
There is a gap between the table itself and its header

### ISSUE THREAD

**Issue by kmakarovaEPAM** [adazzle/react-data-grid#2005]
### Which version of React JS are you using?
☣️ Not officially supported, expect warnings and errors ☣️
- [x]  v16.x.x

### Which browser are you using?
✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x]  Chrome

### I'm submitting a ...
- [x]  🐛 Bug Report
- [ ]  💡 Feature Request

### Issue Details
**What the current behavior is:**
If scroll through the table, there could appear a small gap between the table header and data. The gap size changes dynamically.
When scrolling up, the gap will appear if click vertical scrollbar arrow.

**What the desired behavior is:**
There are no additional gaps between the table header and data.

![demo](https://user-images.githubusercontent.com/62010671/79762664-b8792180-832b-11ea-830f-be28d0ff5591.png)

You can see it [in this demo](https://adazzle.github.io/react-data-grid/docs/examples/render-base-row).

It's important for our app so if any workarounds exist, please provide me with them.
Thanks in advance.

**Comment by egertaia** [comment]
This seems like a gap due to fact that filtering seems to be enabled, but no filterable things has been passed.
Also this demo is from version 5.04.
Try to set `enableHeaderFilters` to false.

**Comment by amanmahajan7** [comment]
This behavior should be fixed in v7 canary. Feel free to open a new issues if you are still facing problems

https://github.com/adazzle/react-data-grid/blob/canary/stories/demos/HeaderFilters.tsx
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--header-filters

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
