### ISSUE TITLE
Copy cell (Ctrl+C) then remove the row containing that cell and paste (Ctrl+V) error.

### ISSUE THREAD

**Issue by emsi-iggy** [adazzle/react-data-grid#2029]
Steps to recreate
1. Copy cell in the last row (Ctrl + C)
2. Remove the row containing that cell (right click menu)
2nd step will result in blue'ish rectangle
3. Paste cell anywhere (Ctrl + V)
4. Whole app error

Image after step 2 (removed 2 rows from the bottom):
![image](https://user-images.githubusercontent.com/44373848/81476112-40a66480-9210-11ea-8176-127a57764ce4.png)

live demo:
https://codesandbox.io/s/rdg-cell-editing-wd1no?file=/src/index.js

My question is:
Is it possible to turn off "copy paste" mode when i know that it is on ?
Or is it possible to find out that it is on?
I would use it in removing row method.

**Comment by amanmahajan7** [comment]
This bug  is fixed in v7 canary and we recommend upgrading. V7 canary also introduced a new `enableCellCopyPaste` to control the copy/paste behavior

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Comment by emsi-iggy** [comment]
Okay, but is there a workaround in previous releases?
It's kinda too late for upgrade for me...
