### ISSUE TITLE
Keeping sorted column and rows between refreshes.

### ISSUE THREAD

**Issue by alvaro1728** [adazzle/react-data-grid#233]
Hi,

A few questions about sorting:

1. Is there a way to initialize the grid with a given sort column and type (asc/desc)?
2. When the grid is refreshed with new rows, I notice the sorted symbol remains on the column header but the new rows aren't sorted accordingly.  What's the best way to address this problem?

Thanks,
Alvaro

**Comment by malonecj** [comment]
Hi, thanks for your questions

1. There is currently no way to pass an initial sort column to the grid with a sort direction. That is something we could implement. As a workaround, you could get access to the grid via a ref from your component and then set the state in your component after the grid has been mounted

``` 
componentDidMount() {
this.refs.grid.setState({sortColumn: 'column1', sortDirection: 'ASC'})
}
``` 

2. Yes, this is something that the grid should handle but does not provide a good way for doing so at the moment. We can change the code so that when new rows are passed to the grid that the `onGridSort` will be called if the sortColumn state is set. In the meantime you could do somethign like this in your component

```
componentWillReceiveProps() {
 if (this.refs.grid.state.sortColumn != null) {
   // sort the rows you pass as props to ReactDataGrid
 }
}
```

**Comment by alvaro1728** [comment]
Thanks for the reply, @malonecj.  Your suggestions worked fine.

**Comment by jbgarr** [comment]
@alvaro1728 Did the solution for your first question actually work? I'm trying to implement this as well, but it's not working for me. I see the caret showing on the column I'm trying to sort, but the data is not sorted. I have set my sort to run in `componentDidMount()` as suggested. My data is being fetched asynchronously, but the data is there once my data grid is created. Any other idea/solutions here?

**Comment by prestond123** [comment]
Thanks - this is exactly what I needed when syncing the sorting widgets, for data loaded across multiple grids.

**Comment by aziz1234** [comment]
How do I implement the same for functional component for the second question ?
