### ISSUE TITLE
general question - examples code

### ISSUE THREAD

**Issue by tamir-jether** [adazzle/react-data-grid#2385]
hey, i wanted to follow up some of the examples code in here: 

https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

but most of them are using components only define locally, with relative imports. 
e.g:
import { CellActionsFormatter, ImageFormatter } from './components/Formatters';

whats the general way to use such code locally using the react-data-grid lib?

**Comment by FPDK** [comment]
I'd recommend placing components in different files, like it's done in the example. This will give you a better overview of the code, instead of having one file that is +1000 lines.

If you need to use the table on multiple pages, you can also make a wrapper component for react-data-grid. That should also give you a better overview of the code.

**Comment by amanmahajan7** [comment]
These components are only for demo purposes and it they need to be used in your project then I would recommend copying them and tweak them as needed.
