### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by juanda99** [adazzle/react-data-grid#257]
Just starting with React Data Grid. It's an awesome and well documented component!

I would like to implement a cell where the user could enter/update several keywords fields with a list of values (autocomplete). Something like:
http://wookiehangover.github.io/react-typeahead/examples/TypeaheadTokenizer-simple.html

Based on demo:

//Custom Formatter component
```
var NameFormatter = React.createClass({
  render:function(){
    var percentComplete = this.props.value 
    return (
      <LinearProgress mode='determinate' value={percentComplete} />
    )
  }
})
```

I've done something similar:
```
var TagsFormatter = React.createClass({
  render:function(){
    var valor = this.props.value 
    return (
      <Tokenizer defaultValue={valor}
        name='spamselect'
        options={
          ['foobar', 'spameggs', 'hameggs',
          'spamfoo', 'spam']} />
    )
  }
})
```

The column is editable, so when I edit it, I think I lost my autocomplete plugin for editing. 
If I put the column no editable I can edit it so I think it's the way to go.
Anything similar before? Should I go this way?
Thank you for your time.

**Comment by malonecj** [comment]
The best way to go about this would be to create a custom editor, instead of a formatter and set that as being the editor for the column in question. It would be good to have an example of how to do this in the docs, but take a look at the autocomplete editor as an example https://github.com/adazzle/react-data-grid/blob/master/src/addons/editors/AutoCompleteEditor.js

Your editor needs to implement two methods. Both these methods are called by the editorContainer
 - getInputNode -> returns the html node of the main editing input
 - getValue -> returns the current value of the editor, directly before commiting a cell value

**Comment by juanda99** [comment]
Thank you. Came back from holidays :-)

I don't get all your answer :-(

... how do you call the editor?

Should I use a parameter editor  like the one I use for toolbar?

```
var Toolbar = ReactDataGrid.Toolbar
 <ReactDataGrid columns={columns} rowGetter={this.rowGetter} rowsCount={this.state.rows.length}
            toolbar={<Toolbar enableFilter={true}/>} onAddFilter={this.handleFilterChange}
            editor ={....}
             enableCellSelect={true} onRowUpdated={this.handleRowUpdated} minHeight={500} />
        </div>
```

Curently the only way I have is from the column field with editable field, but it's boolean:

```
  {
    key: 'filters_locale',
    name: 'Filters',
    resizable: true,
    filterable: true,
    editable: true
  }
```

Or should I change editorContainer where you call SimpleTextEditor? Can I have different Editor for different columns?

**Comment by juanda99** [comment]
Upps, I missed this:
http://adazzle.github.io/react-data-grid/examples.html#/editors
