### ISSUE TITLE
when updating `rows` stored in react-query cache, `renderCell` fires with the old value

### ISSUE THREAD

**Issue by Liooo** [adazzle/react-data-grid#3299]
## Describe the bug 

Depending on how `rows` state is managed, there's a weird `renderCell` trigger after updating the value through `rederEditCell`. Here's the minimum reproducible app in [[codesandbox]](https://codesandbox.io/s/rdg-state-vs-rqcache-8g94tc?file=/src/App.tsx)

#### A. when `rows` are stored in react-query cache

As you can see in the console log, there's an unnecessary renderCell call with the old value, which is causing cell blink.

https://github.com/adazzle/react-data-grid/assets/1630378/29faf540-0e90-40fd-9934-733e4dadd22e

#### B. when `rows` are stored in useState

There's no unnecessarily `renderCell`, nor the blinking.

https://github.com/adazzle/react-data-grid/assets/1630378/84e6a238-39eb-4658-bd98-3076a823e4f0

## To Reproduce 

1. in codesandbox tick "A. react-query", edit cell value, then blur from the input
2. tick "B. useState", do the same

[[codesandbox]](https://codesandbox.io/s/rdg-state-vs-rqcache-8g94tc?file=/src/App.tsx)

## Expected behavior 

unnecessary renderCell does not trigger and the cell doesn't blink when with react-query cache

## Environment

- `react-data-grid` version: 7.0.0-beta34
- `react`/`react-dom` version: 18.2.0 / 18.2.0

## Additional context 

- it seems pretty solid that react-query does rerender after updating the cache, and the component is actually rerendering in codesandbox
    - https://github.com/TanStack/query/issues/326
    - https://github.com/TanStack/query/discussions/758
 - it's a common way to perform optimistic update
    - https://tanstack.com/query/v4/docs/react/guides/optimistic-updates
- I'm not really sure but could [syncExternalStore](https://react.dev/reference/react/useSyncExternalStore) and [flushSync](https://react.dev/reference/react-dom/flushSync) be affecting somehow?

**Comment by Liooo** [comment]
@amanmahajan7 

Would you mind giving a look? The example code should be pretty minimal.

**Comment by Liooo** [comment]
@nstepien sorry for bothering really, but need some help 🙏

**Comment by paustint** [comment]
@Liooo - you should use the update APIs instead of manually the update directly in your editor component.
Also, your example does not handle the case where a user presses "enter" in which case the value is not saved

In your render cell editor, you should call `onRowChange` and `onChange` provided by the table callback instead of directly updating your rows from that component, then handle actually updating the rows using onRowsChange.

Here is a working example:
https://codesandbox.io/s/rdg-state-vs-rqcache-forked-y9jdp9?file=/src/App.tsx


Refer to the examples from the website demo:
https://github.com/adazzle/react-data-grid/blob/main/website/demos/AllFeatures.tsx

And the built-in text editor component which you can use or at refer to when building your own editor:
https://github.com/adazzle/react-data-grid/blob/main/src/editors/textEditor.tsx

**Comment by Liooo** [comment]
It worked, thank you @paustint!
I thought I tried pretty much the same which wasn't working back then, and found out you kindly added RQ's `{keepPreviousData: true}` as well and this is also a must have key.
