### ISSUE TITLE
Get Value of DoubleClicked Cell

### ISSUE THREAD

**Issue by Wickerman2** [adazzle/react-data-grid#367]
Hello!

I need some help getting the value of the cell that I've doubleclicked on. 

I tried using the following code: 
  key: 'SOURCE',
  name: 'Source',
      events: {
      onDoubleClick: function(ev, args) {
        console.log(args);
      },
    }

Where I am able to get the rowIdx and idx, but is there a similar way to get the value of the doubleclicked cell...?

**Comment by diogofcunha** [comment]
Hi @Wickerman2 for now the only way to do that is to get the value based on the coordinates, column events don't retrieve cell values as a arg as you can check [in here](https://github.com/adazzle/react-data-grid/blob/master/src/ReactDataGrid.js#L115).

That can be a discussed feature for the future, if you fell like it could be a good improvement fell free to open an issue about it. (We will accept a PR for it or place it in the road map).

**Comment by pnaika** [comment]
Have similar issue, need a help. Is there a way to get the column value when we click on the particular Cell in react-data-grid. when I do onClick event in the row, I get this._Column info., but I want the value from the Cell, So that I can use that value and Navigate to particular page when an ID is clicked, I am referring to this, `http://adazzle.github.io/react-data-grid/examples.html#/column-events` `http://adazzle.github.io/react-data-grid/scripts/example19-column-events.js`   . Any help will be appreciated, thanks
