### ISSUE TITLE
Add calculated field example [Help wanted]

### ISSUE THREAD

**Issue by dulguun0225** [adazzle/react-data-grid#444]
Good performance calculated field example would be very helpful. 
Maybe can someone just help me find good example and close it?

**Comment by diogofcunha** [comment]
Hi @dulguun0225, what do you mean by that?

**Comment by dulguun0225** [comment]
Column c = column a + column b. When a user enters value in a and b, c's value becomes a+b

**Comment by diogofcunha** [comment]
React Data Grid supports **dependent values**.
To define a dependent value for a column A all you need to do is create a shape with the correct column names that column A depends on and export it on the editor.

Let's imagine you're use case, **column C depends on column A and column B**, so in column C editor you would do something like this.

```
const columnCEditor = (props) => { ... }
const dependentColumns = {
   columnA: Proptypes.number,
   columnB: Proptypes.number
};

export default columnCEditor;
export { dependentColumns  };
```
You need to make sure that you have a easy way to load your editors, I would put them all the same folder and add a `index.js` to export them all.

The trick comes now, `ReactDataGrid` supports a prop called `onGridRowsUpdated` that callback will be triggered every time a cell value is committed with the following pararms:

```
cellKey: string;
fromRowIdx: number;
rowsToUpdate: Array;
rowDataChanged: Object;
```

At this stage you can get your editor based on the `cellKey` and that means that you can also get the dependent columns for that editor, after this you can apply any formula you desire and apply the updated cell values depending on the way you store your rows. The way you do this always depends on the way you store things, I would recommend you to use flux or redux if your app can escalate otherwise try to make the state simple so that you can execute this operations without adding extra complexity.

**Comment by dulguun0225** [comment]
Thanks for the help!
