### ISSUE TITLE
Set default sorting column and sorting direction while initializing

### ISSUE THREAD

**Issue by JosephGu** [adazzle/react-data-grid#547]
Hi team,

I'd like to set a arrow up icon for specified column while initializing,(i.e., We can handle the sorting in the backend service, and just need to set the icons to the specified column)

How could I implement it?

**Comment by tdzienniak** [comment]
Hey, I've just made PR resolving this issue. I have some questions about this functionality:
- should setting sort column and direction initially trigger `onGridSort` callback?
- or maybe user should provide already sorted data?
- shoud there be a check that column in `sortColumn` prop is sortable?

**Comment by mgscreativa** [comment]
Hi! In my case I'm using meteor to fetch a paginated list. Triggering onGridSort handler calls a subscription that sorts the data server side then publishes the paginated data back to the client. To get that subscription data I must use **createContainer** HOC.

In my scenario, it will be just cool to have those props to tweak them in my render function, so after subscription is ready, the render function should get the sort order and column and set that on the ReactDataGrid component because the data got sorted on the server.

Please merge this!

Thanks!

**Comment by GlebDolzhikov** [comment]
Why version 3 doesn't contain it? plss merge it

**Comment by amanmahajan7** [comment]
This feature has been added in #649
