### ISSUE TITLE
react-data-grid with es5

### ISSUE THREAD

**Issue by rina-andria** [adazzle/react-data-grid#595]
Hi,
I tried to search a working example of this package using es5.
Syntax like:
import ReactDataGrid from 'react-data-grid';
...

render() {
return <ReactDataGrid ...>;
}

I get the following issue when loading the grid (page):
- Invalid argument supplied to oneOf, expected an instance of array.
- Cell: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.
- Failed prop type: The prop `isScrolling` is marked as required in `Cell`, but its value is `undefined`.
- And the style is not applied

Can you please let me know what am I missing ?

Thanks a lot!

**Comment by malonecj** [comment]
Can you post all the props you are passing to ReactDataGrid. Looks like you you are passing some invalid props.

As for the style, for now you need to directly reference the css file in the dist folder. This will be fixed in v2 which is close to being ready

https://github.com/adazzle/react-data-grid/pull/541

**Comment by rina-andria** [comment]
Thanks,
Here are the props I pass:
<ReactDataGrid enableCellSelect={true} columns={columns} rowGetter={this.rowGetter.bind(this)} rowsCount={this.state.rows.length} minHeight={500} onRowUpdated={this.handleRowUpdated.bind(this)} />

I just translate the editable example in: http://adazzle.github.io/react-data-grid/examples.html#/editable

**Comment by diogofcunha** [comment]
Hi @rina-andria.

The first think you pointed out was fixed in version 1.0.82.
Point 2 and 3 are know issues, react warnings that just show up on development, and they will not affect your grid.
For the 4th, for now you need to import our styles from the dist folder on npm or copy them to your own css and override whatever you need to. That will change after version 2.0.0 and you will get all that for free when you install the package, being able to override just the styles you intend to
