### ISSUE TITLE
Display multiple values in a cell and specify which value to use for sorting 

### ISSUE THREAD

**Issue by nextofsearch** [adazzle/react-data-grid#734]
Hi,

I am new to react-data-grid and see if I can display multiple values in a cell and specify which value (i.e. hidden input) to use for sorting. (Please check out [this image](http://i63.tinypic.com/24dpojn.png)). The cell has 2 values: one is an original value and the other is a variation compared to its control group. The current implementation is done using jQuery dataTable and I am searching for an alternative since it is not compatible with React. The way I did with dataTables is adding a number using input tag as hidden and set sorting to be done with the input tag in the cell, not just any number.

**Comment by Whythawye** [comment]
If you use the custom cell formatter functionality (http://adazzle.github.io/react-data-grid/examples.html#/custom-formatters) you can pass an object instead of a string and then display only the part of the value you want to. And then in the sort function you specify the other part of the value for sorting. I ran into a similar need when I was mapping validation errors to cell data for display. The problem I ran into was that I couldn't edit the cells using this method because the editor was grabbing the object and not the value inside the object. If you don't need to edit the cells, you should be good, though.
