### ISSUE TITLE
Million Rows example broken on Chrome

### ISSUE THREAD

**Issue by csvan** [adazzle/react-data-grid#786]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**
Yes
> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[ ] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[X] Chrome 58
```

```
Should work:
[X] Firefox
[X] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Reproduction of the problem**

Scrolling through the Million Rows example at http://adazzle.github.io/react-data-grid/examples.html#/one-million-rows causes erratic display behavior under certain circumstances.

Using free mouse-wheel scrolling: grid turns white, and stays that way until user scrolls in other direction.
![onemillionrowsbroken2](https://cloud.githubusercontent.com/assets/1127729/25943287/b1b93664-363f-11e7-935e-627f2c72f07c.PNG)

Dragging the vertical scroll bar to about the middle of the grid: cell borders vanish:

![onemillionrowsbroken1](https://cloud.githubusercontent.com/assets/1127729/25943335/d01dac16-363f-11e7-8694-fbb8ddf0328e.PNG)
*What is the motivation / use case for changing the behavior?**

**Comment by jpdriver** [comment]
hey @csvan -- this is a known limitation because of the way rendering currently works.

The short explanation is that we render Grids that take up more than the maximum px height of the DOM. (This varies browser-to-browser but in Chrome's case is 33,554,428px).

I'm hoping to fix this in a future release (see https://github.com/adazzle/react-data-grid/issues/772), and here's a screenshot of the fix in action:

<img width="1440" alt="screen shot 2017-05-04 at 3 48 49 pm" src="https://cloud.githubusercontent.com/assets/2393035/25943632/6d70e08a-3638-11e7-8759-3aa858640601.png">

**Comment by csvan** [comment]
@jpdriver that's great to hear! Thanks for all the hard work :)
