### ISSUE TITLE
Reverse default Sort Order

### ISSUE THREAD

**Issue by lord-xeon** [adazzle/react-data-grid#829]
> **HAVE YOU ALREADY SEARCHED FOR SIMILAR ISSUES? PLEASE HELP US OUT AND DOUBLE-CHECK FIRST!**

> **ALSO, PLEASE DON'T BE THAT PERSON WHO DELETES THIS TEMPLATE. IT'S HERE FOR A REASON.**

> **THANKS!**

**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[x] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[ ] IE 9 / IE 10 / IE 11
[ ] Edge
[x] Chrome
```

```
Should work:
[ ] Firefox
[ ] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**
When sorting columns on the grid, the first direction that is given is ASC

**Expected/desired behavior**
Give the ability to make the first sort direction DESC

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
I want users to sort the of data descending on their first click of the column header.

**Comment by rlreamy** [comment]
I would also love this feature.  We have a table of data that contains some columns that you would want sorted ascending by default (names, p-value, etc).  Then, we have several other columns where the most interesting/significant values are the largest (fold change, r-value) and we want those to be sorted to the top of the list when the user initially clicks the row.

We have accomplished this by coding our comparators to do this, however, the indicator is reversed, and it means some rather convoluted and confusing logic (since we are basically doing the opposite of the passed in sort order for those columns).
