### ISSUE TITLE
One Million row example does not render all rows

### ISSUE THREAD

**Issue by Martynas-P** [adazzle/react-data-grid#87]
The example which renders one million rows stops rendering rows after 958699 rows as well as the borders between rows are missing.

![image](https://cloud.githubusercontent.com/assets/2590908/10425235/be88d6c6-70cd-11e5-8c86-ea8ff2625ce4.png)

**Comment by bakesteve** [comment]
sorry you didn't hear back on this - we'll make sure we get to it, just had a hectic backlog recently

**Comment by alistairjcbrown** [comment]
For context on why this is limited, it's due to the height of the scrolling div; it appears that the pixel size rendered by the browser has a set limit: http://stackoverflow.com/a/16637689
On Chrome/Firefox is around 33.5 million pixels. On the 1 million row table, each row is 35px in height, so `33,554,428 / 35 = 958,698`. Technically the rows below are rendered, but there's no way to scroll to them as the height of the div has been maxed.

Internally to the scrolling div is a placeholder element with the height set that takes up the same space as rendered rows would. This allows you to scroll, but keeps the DOM small by not rendering the actual rows; that's the power of this component.
However, the scroll created on the scrolling div when it contains a 10 million pixel high placeholder element vs. 30 million pixels high placeholder element should be relatively similar - both will appear to the user as large amounts of space to scroll, though one is a third smaller than the other.

Perhaps there's a way to keep the overall height of the scrolling div below the browser limit, but still provide the appearance of scrolling to data, even for a number of rows which would actually take up more than the browser limit if all were rendered in the DOM?

**Comment by bakesteve** [comment]
ah - ok, that'd a good find @alistairjcbrown 
we could just max out the physical display, so you get a very big scroller, but then just manage the extra data in the canvas component. We'd just need a map so that that when viewport tells canvas to scroll, it understands this relationship (so adjusts that when the scroll moves by 35px, that is 1 row if we havent capped it, but more if we have). In theory, that should be fairly straightforward and easily testable

On a side note, anyone out there actually using this with >1 million rows? be good to hear how you handle the data loads as we've yet to natively provide a mechanism for lazy loads, and been debating if that should be part of the component, and add-on, or take the library approach and you bring your own lazy loading. (probably erring towards the add on approach, or at least a working example, FWIW)
