### ISSUE TITLE
a way to remove the header from a react-data-grid

### ISSUE THREAD

**Issue by soma83** [adazzle/react-data-grid#879]
Is there a way to remove the header from a react-data-grid?

**Comment by andrewlorenz** [comment]
good question, deserves an answer!  I wish I knew, as I want to do so too.  Tried <ReactDataGrid headerRowHeight={0} /> but that didn't work ...

**Comment by arkoblog** [comment]
I used the following custom style hack to hide the header.
`  .react-grid-Header {
    display:none !important;
  }

  .react-grid-Viewport {
    top: 0px !important;
  }`

**Comment by fierascu** [comment]
in the JSX I added a wrapper:
```
    return (
      <div className = {this.showHeader ? "" : "noHeaderWrapper "} > 
            <ReactDataGrid  />
      </div>
      );
```

and in external css I used the code from answer from @arkoblog!
```
.noHeaderWrapper .react-grid-Header {
  display: none !important;
}
.noHeaderWrapper  .react-grid-Viewport {
  top: 0px !important;
}
```

**Comment by patrickvienneau** [comment]
I've found challenges with the above solution when adding rows to the `react-data-gid` on-the-fly. My solution was the following (based off of [fierascu's solution](https://github.com/adazzle/react-data-grid/issues/879#issuecomment-414938583):

```jsx
<ReactDataGrid className='noHeaderWrapper' headerRowHeight={1}  />
```

```scss
.noHeaderWrapper .react-grid-Header {
    display: none;
}
```

As mentioned thru https://github.com/adazzle/react-data-grid/issues/834:

> setting headerRowHeight=0, the height will be considered as undefined and it will use the default row height.

So setting a 1px will get the header as close to 0 as possible, and we can simply hide the header in CSS. The `top` position doesn't work, unfortunately, as it messes on-the-fly positional calculations of the grid. The above code will likely cause a 1px vertical offset to the grid relative to the page, but due to our repository heavily extending `react-data-grid`, this was favourable to row content being vertically offset to the `top` position.

**Comment by RavenHursT** [comment]
Seriously? There's no way to have a table w/o a header?
