### ISSUE TITLE
CheckboxEditor throwing 'checked' prop for a field without onChange handler

### ISSUE THREAD

**Issue by jdh-invicara** [adazzle/react-data-grid#949]
### Which version of React JS are you using?

- [x] v15.6.x

### Which browser are you using?

- [x] Chrome

---

### I'm submitting a ...

- [x] 🐛 Bug Report
---

### Issue Details

I have a grid on a dialog (a hidden div that is hidden or shown).  The grid has rowSelection.showCheckbox: true.  When I show my dialog the second time I get the following warning:

```
Warning: Failed form propType: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `CheckboxEditor`.
```

And the previously selected rows are still selected

**Comment by dklanac** [comment]
I believe it's complaining about the `input` element not having an `onChange` handler. It makes sense that there isn't one there, since this is actually a CSS checkbox implementation and not a form element that the user directly interacts with.

```
handleChange: function handleChange(e) {
 9378       this.props.column.onCellChange(this.props.rowIdx, this.props.column.key, this.props.dependentValues, e);
 9379     },
 9380     render: function render() {
 9381       var checked = this.props.value != null ? this.props.value : false;
 9382       var checkboxName = 'checkbox' + this.props.rowIdx;
 9383       return React.createElement(
 9384         'div',
 9385         { className: 'react-grid-checkbox-container checkbox-align', onClick: this.handleChange },
 9386         React.createElement('input', { className: 'react-grid-checkbox', type: 'checkbox', name: checkboxName, checked: checked }),
 9387         React.createElement('label', { htmlFor: checkboxName, className: 'react-grid-checkbox-label' })
 9388       );
 9389     }
```

One idea that I'll float out there is that this component could be modified where the input does have an `onChange` handler that updates the `input` checkbox state. The `onClick` handler on the `div` would just need to be updated to become a delegator function that grabs the `input` checkbox DOM element and calls its native `click()` method to simulate a user directly clicking the box that's technically hidden by the CSS checkbox.

Thoughts?
