### ISSUE TITLE
rowGetter is taking lot of time and blocking rendering

### ISSUE THREAD

**Issue by shouvikbhuiyan1990** [adazzle/react-data-grid#961]
Is it possible to write rowGetter function asyncronusly so that it doesnot block my UI rendering ? I have a grid of 1000 X 67 and the initial rendering is taking a lot of time.

**Comment by martinnov92** [comment]
Hello, did you find any solution for this? I will need this as well :/

**Comment by diogofcunha** [comment]
Hi guys. 

Not sure I understand the requirement in here.

Javascript runs on a single thread, making it async would cause the same issues as doing in a sync maner, the only way that making this async could work for you is if you're retrieving rows on demand from an external source.

There no reason inside rdg code for your rowGetter to be slow, if it is running slow it is possibly because your data modelling isn't correct, getting rows should be O(1) operation, if it isn't you need to figure out why in your internal code and if you don't have any chance to change that fact maybe think about memoization 

You can drop me an email with the rowGetter code for me to have a look if you wish
